extends Node
@warning_ignore("unused_signal")
signal _register_puzzle_piece(piece_node: Node3D, parent: Node3D)
@warning_ignore("unused_signal")
signal _update_puzzle_piece(piece_node: Node3D, variable)
@warning_ignore("unused_signal")
signal _puzzle_completed(puzzle_state: bool)
@warning_ignore("unused_signal")
signal _update_current_level(level_name: String)
@warning_ignore("unused_signal")
signal _win_state()
